name: Deploy React Romafla

on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy via FTP MarceloReact
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: digitalbos.com.br
          username: ${{ secrets.USERNAME }}
          password: 1532@RAIane
          local-dir: dist/
          server-dir: marcelo/
    